const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('novaAssist', {
  executeCommand: (input) => ipcRenderer.invoke('execute-command', input),
  voiceListen: () => ipcRenderer.invoke('voice-listen'),
  voiceSpeak: (text) => ipcRenderer.invoke('voice-speak', text),
  takeScreenshot: () => ipcRenderer.invoke('take-screenshot'),
  onOverlayUpdate: (cb) => ipcRenderer.on('overlay-update', (_e, data) => cb(data)),
  checkAccessibility: () => ipcRenderer.invoke('check-accessibility'),
  checkAllPermissions: () => ipcRenderer.invoke('check-all-permissions'),
  requestScreenRecording: () => ipcRenderer.invoke('request-screen-recording'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  verifyAws: (creds) => ipcRenderer.invoke('verify-aws', creds),
  verifyPicovoice: (key) => ipcRenderer.invoke('verify-picovoice', key),
  installDeps: () => ipcRenderer.invoke('install-deps'),
  saveConfig: (config) => ipcRenderer.invoke('save-config', config),
  completeSetup: () => ipcRenderer.invoke('complete-setup'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveSetupStep: (step) => ipcRenderer.invoke('save-setup-step', step),
  restartApp: () => ipcRenderer.invoke('restart-app'),
  onDepsOutput: (cb) => ipcRenderer.on('deps-output', (_e, data) => cb(data)),
});
